import { resizeImage } from '@starter-kit/utils/image';
import Image from 'next/image';
import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import ErrorPage from 'next/error';
import Head from 'next/head';
import Link from 'next/link';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { CoverImage } from '../components/cover-image';
import { DateFormatter } from '../components/date-formatter';
import { Layout } from '../components/layout';
import { EnhancedMarkdown } from '../components/enhanced-markdown';
import { TableOfContents } from '../components/table-of-contents';
import {
	PageByPublicationDocument,
	PageByPublicationQuery,
	PageByPublicationQueryVariables,
	PostFullFragment,
	PublicationFragment,
	SinglePostByPublicationDocument,
	SinglePostByPublicationQuery,
	SinglePostByPublicationQueryVariables,
	SlugPostsByPublicationDocument,
	SlugPostsByPublicationQuery,
	SlugPostsByPublicationQueryVariables,
	StaticPageFragment,
} from '../generated/graphql';

type Props =
	| {
			post: PostFullFragment;
			page: null;
			publication: PublicationFragment;
	  }
	| {
			post: null;
			page: StaticPageFragment;
			publication: PublicationFragment;
	  };

const Post = (publication: PublicationFragment, post: PostFullFragment) => {
		const vibrantSyntaxHighlighting =
		`/* Vibrant Syntax Highlighting Theme - Force Override */
		.hljs {
			display: block !important;
			overflow-x: auto;
			padding: 1rem;
			background: linear-gradient(135deg, #0f0f23 0%, #1a1a2e 50%, #16213e 100%) !important;
			color: #f8f8f2 !important;
			border-radius: 12px;
			line-height: 1.6;
			font-size: 0.9rem;
		}
		
		/* Keywords - Bright Pink/Magenta */
		.hljs-keyword,
		.hljs-selector-tag,
		.hljs-built_in,
		.hljs-name,
		.hljs-tag { color: #ff6ac7 !important; font-weight: 600 !important; }
		
		/* Strings - Bright Green */
		.hljs-string,
		.hljs-title,
		.hljs-section,
		.hljs-attribute,
		.hljs-literal,
		.hljs-template-tag,
		.hljs-template-variable,
		.hljs-type,
		.hljs-addition { color: #57ff57 !important; }
		
		/* Numbers - Bright Orange */
		.hljs-number,
		.hljs-symbol,
		.hljs-bullet,
		.hljs-variable,
		.hljs-template-variable,
		.hljs-literal { color: #ff9500 !important; font-weight: 500 !important; }
		
		/* Functions - Bright Cyan */
		.hljs-title.function_,
		.hljs-function .hljs-title,
		.hljs-attr,
		.hljs-property,
		.hljs-attribute { color: #00d4ff !important; font-weight: 500 !important; }
		
		/* Comments - Bright Purple */
		.hljs-comment,
		.hljs-code,
		.hljs-meta { color: #bd93f9 !important; font-style: italic !important; opacity: 0.8 !important; }
		
		/* Classes - Bright Yellow */
		.hljs-class .hljs-title,
		.hljs-title.class_,
		.hljs-title.class .hljs-inherited,
		.hljs-subst { color: #f1fa8c !important; font-weight: 600 !important; }
		
		/* Operators - Bright Red */
		.hljs-operator,
		.hljs-regexp,
		.hljs-selector-attr,
		.hljs-selector-class,
		.hljs-selector-id,
		.hljs-selector-pseudo { color: #ff5555 !important; font-weight: 500 !important; }
		
		/* Variables - Bright Blue */
		.hljs-params,
		.hljs-variable.language_,
		.hljs-variable.constant_ { color: #8be9fd !important; }
		
		/* Deletion */
		.hljs-deletion { color: #ff5555 !important; background-color: rgba(255, 85, 85, 0.1) !important; }
		
		/* Addition */
		.hljs-addition { color: #57ff57 !important; background-color: rgba(87, 255, 87, 0.1) !important; }
		
		/* Strong and emphasis */
		.hljs-strong { font-weight: 700; }
		.hljs-emphasis { font-style: italic; }
		
		/* Links */
		.hljs-link { color: #ff6ac7; text-decoration: underline; }
		
		/* Language-specific enhancements */
		.hljs-tag .hljs-name { color: #ff6ac7; }
		.hljs-tag .hljs-attr { color: #00d4ff; }
		.hljs-tag .hljs-string { color: #57ff57; }
		
		/* JSON specific */
		.language-json .hljs-attr { color: #00d4ff; }
		.language-json .hljs-string { color: #57ff57; }
		.language-json .hljs-number { color: #ff9500; }
		.language-json .hljs-literal { color: #bd93f9; }
		
		/* CSS specific */
		.language-css .hljs-selector-tag { color: #ff6ac7; }
		.language-css .hljs-selector-class { color: #f1fa8c; }
		.language-css .hljs-selector-id { color: #00d4ff; }
		.language-css .hljs-attribute { color: #8be9fd; }
		.language-css .hljs-number { color: #ff9500; }
		.language-css .hljs-string { color: #57ff57; }
		
		/* JavaScript specific */
		.language-javascript .hljs-function { color: #ff6ac7; }
		.language-javascript .hljs-title.function_ { color: #00d4ff; }
		.language-javascript .hljs-variable { color: #8be9fd; }
		.language-javascript .hljs-property { color: #f1fa8c; }`

			const tagsList = (post.tags ?? []).map((tag) => {
				// Truncate tag names longer than 15 characters
				const displayTag = tag.slug.length > 15 ? `${tag.slug.substring(0, 15)}...` : tag.slug;
				
				return (
					<li key={tag.id} className="flex-shrink-0">
						<Link
							href={`/tag/${tag.slug}`}
							className="inline-flex items-center rounded-full bg-gray-100 dark:bg-neutral-800 hover:bg-primary-100 dark:hover:bg-primary-900/30 border border-gray-200 dark:border-neutral-700 hover:border-primary-200 dark:hover:border-primary-600 px-2 py-0.5 text-xs font-medium text-gray-700 dark:text-neutral-300 hover:text-primary-700 dark:hover:text-primary-300 transition-all duration-200 max-w-[120px] truncate"
							title={`#${tag.slug}`}
						>
							<span className="truncate">#{displayTag}</span>
						</Link>
					</li>
				);
			});

	const coverImageSrc = !!post.coverImage?.url
		? resizeImage(post.coverImage.url, {
				w: 1600,
				h: 840,
				c: 'thumb',
		  })
		: undefined;

	return (
		<>
			<Head>
				<title>{post.seo?.title || post.title}</title>
				<link rel="canonical" href={post.url} />
				<meta name="description" content={post.seo?.description || post.subtitle || post.brief} />
				<meta property="twitter:card" content="summary_large_image"/>
				<meta property="twitter:title" content={post.seo?.title || post.title} />
				<meta property="twitter:description" content={post.seo?.description || post.subtitle || post.brief} />
				<meta
					property="og:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: vibrantSyntaxHighlighting }}></style>
			</Head>
			{/* Article Header */}
			<div className="space-y-4 sm:space-y-6">
				<h1 className="text-fluid-hero font-bold leading-tight tracking-tight text-black dark:text-white">
					{post.title}
				</h1>
				<div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 text-sm sm:text-base text-neutral-600 dark:text-neutral-400">
					<DateFormatter dateString={post.publishedAt} />
					{post.readTimeInMinutes && (
						<>
							<span className="hidden sm:block">&bull;</span>
							<span>{post.readTimeInMinutes} min read</span>
						</>
					)}
					{post.author && (
						<>
							<span className="hidden sm:block">&bull;</span>
							<span>By {post.author.name}</span>
						</>
					)}
				</div>
			</div>
			{/* Cover Image */}
			{!!coverImageSrc && (
				<div className="w-full my-4 sm:my-6 lg:my-8">
					<div className="relative aspect-video w-full overflow-hidden rounded-xl bg-gray-100 dark:bg-neutral-800">
						<Image
							src={coverImageSrc}
							alt={post.title}
							fill
							className="object-cover transition-transform duration-300 hover:scale-105"
							priority
							sizes="(max-width: 768px) 100vw, (max-width: 1200px) 80vw, 70vw"
							placeholder="blur"
							blurDataURL="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAIAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAhEAACAQMDBQAAAAAAAAAAAAABAgMABAUGIWGRkqGx0f/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAECEgMRkf/aAAwDAQACEQMRAD8AltJagyeH0AthI5xdrLcNM91BF5pX2HaH9bcfaSXWGaRmknyJckliyjqTzSlT54b6bk+h0R//2Q=="
						/>
					</div>
				</div>
			)}
			{/* Table of Contents - Mobile */}
			<TableOfContents showOnMobile={true} />
			
			{/* Article Content with Desktop TOC */}
			<div className="relative">
				{/* Desktop Table of Contents - Positioned absolutely */}
				<div className="hidden xl:block absolute -right-96 top-0 w-80">
					<TableOfContents showOnMobile={false} />
				</div>
				
				{/* Main Content */}
				<div className="prose prose-sm sm:prose-base lg:prose-lg xl:prose-xl prose-gray dark:prose-invert max-w-none prose-headings:text-black dark:prose-headings:text-white prose-p:leading-relaxed prose-table:overflow-x-auto prose-img:max-w-full prose-img:h-auto prose-video:max-w-full prose-iframe:max-w-full content-overflow-fix">
					<EnhancedMarkdown contentMarkdown={post.content.markdown} />
				</div>
			</div>
			{/* Tags Section */}
			{(post.tags ?? []).length > 0 && (
				<div className="w-full border-t border-gray-200 dark:border-neutral-700 pt-4">
					<div className="flex flex-col gap-2">
						<span className="text-xs font-medium text-gray-500 dark:text-neutral-400 uppercase tracking-wide">Topics</span>
						<div className="-mx-1 sm:mx-0">
							<ul className="flex items-center gap-1.5 max-w-full overflow-x-auto px-1 sm:px-0 pb-1 scrollbar-hide">
								{tagsList}
							</ul>
						</div>
					</div>
				</div>
			)}
		</>
	);
};

const Page = (page: StaticPageFragment) => {
	const title = page.title;
	return (
		<>
			<Head>
				<title>{title}</title>
			</Head>
			<EnhancedMarkdown contentMarkdown={page.content.markdown} />
		</>
	);
};

export default function PostOrPage({ publication, post, page }: Props) {
	if (!post && !page) {
		return <ErrorPage statusCode={404} />;
	}

	return (
		<AppProvider publication={publication} post={post}>
			<Layout>
			<Container className="mx-auto flex w-full max-w-4xl xl:max-w-7xl flex-col items-stretch gap-8 px-4 py-8 sm:px-6 sm:py-12 lg:px-8 lg:py-16 xl:px-12 overflow-hidden relative">
				<article className="flex flex-col items-start gap-6 sm:gap-8 lg:gap-10 pb-8 lg:pb-10 w-full overflow-hidden xl:mr-96">
					{post ? Post(publication, post) : Page(page)}
				</article>
			</Container>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params) {
		throw new Error('No params');
	}
	const data = await request<SinglePostByPublicationQuery, SinglePostByPublicationQueryVariables>(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SinglePostByPublicationDocument,
		{
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
			slug: params.slug,
		},
	);

	// Extract the post data from the GraphQL response
	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const post = publication.post;
	if (!post) {
		const staticPageData = await request<PageByPublicationQuery, PageByPublicationQueryVariables>(
			process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
			PageByPublicationDocument,
			{
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				slug: params.slug,
			},
		);

		const page = staticPageData.publication?.staticPage;
		if (!page) {
			return {
				notFound: true,
			};
		}
		return {
			props: {
				post: null,
				page,
				publication,
			},
			revalidate: 1,
		};
	}

	return {
		props: {
			post,
			page: null,
			publication,
		},
		revalidate: 1,
	};
};

export async function getStaticPaths() {
	const data = await request<SlugPostsByPublicationQuery, SlugPostsByPublicationQueryVariables>(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SlugPostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const postSlugs = (data.publication?.posts.edges ?? []).map((edge) => edge.node.slug);

	return {
		paths: postSlugs.map((slug) => {
			return {
				params: {
					slug: slug,
				},
			};
		}),
		fallback: 'blocking',
	};
}
