import { resizeImage } from '@starter-kit/utils/image';
import Image from 'next/image';
import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import ErrorPage from 'next/error';
import Head from 'next/head';
import Link from 'next/link';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { CoverImage } from '../components/cover-image';
import { DateFormatter } from '../components/date-formatter';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MarkdownToHtml } from '../components/markdown-to-html';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	PageByPublicationDocument,
	PageByPublicationQuery,
	PageByPublicationQueryVariables,
	PostFullFragment,
	PublicationFragment,
	SinglePostByPublicationDocument,
	SinglePostByPublicationQuery,
	SinglePostByPublicationQueryVariables,
	SlugPostsByPublicationDocument,
	SlugPostsByPublicationQuery,
	SlugPostsByPublicationQueryVariables,
	StaticPageFragment,
} from '../generated/graphql';

type Props =
	| {
			post: PostFullFragment;
			page: null;
			publication: PublicationFragment;
	  }
	| {
			post: null;
			page: StaticPageFragment;
			publication: PublicationFragment;
	  };

const Post = (publication: PublicationFragment, post: PostFullFragment) => {
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';

			const tagsList = (post.tags ?? []).map((tag) => (
				<li key={tag.id}>
					<Link
						href={`/tag/${tag.slug}`}
						className="inline-flex items-center rounded-full border border-gray-300 dark:border-neutral-600 px-3 py-1 text-xs sm:text-sm font-medium text-gray-600 dark:text-neutral-300 hover:bg-primary-50 hover:border-primary-300 dark:hover:bg-primary-900/20 dark:hover:border-primary-600 transition-colors duration-200 whitespace-nowrap max-w-[200px] overflow-hidden text-ellipsis"
						title={`#${tag.slug}`}
					>
						#{tag.slug}
					</Link>
				</li>
			));

	const coverImageSrc = !!post.coverImage?.url
		? resizeImage(post.coverImage.url, {
				w: 1600,
				h: 840,
				c: 'thumb',
		  })
		: undefined;

	return (
		<>
			<Head>
				<title>{post.seo?.title || post.title}</title>
				<link rel="canonical" href={post.url} />
				<meta name="description" content={post.seo?.description || post.subtitle || post.brief} />
				<meta property="twitter:card" content="summary_large_image"/>
				<meta property="twitter:title" content={post.seo?.title || post.title} />
				<meta property="twitter:description" content={post.seo?.description || post.subtitle || post.brief} />
				<meta
					property="og:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }}></style>
			</Head>
			{/* Article Header */}
			<div className="space-y-3 sm:space-y-4">
				<h1 className="text-2xl sm:text-3xl lg:text-4xl xl:text-5xl font-bold leading-tight tracking-tight text-black dark:text-white">
					{post.title}
				</h1>
				<div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 text-sm sm:text-base text-neutral-600 dark:text-neutral-400">
					<DateFormatter dateString={post.publishedAt} />
					{post.readTimeInMinutes && (
						<>
							<span className="hidden sm:block">&bull;</span>
							<span>{post.readTimeInMinutes} min read</span>
						</>
					)}
					{post.author && (
						<>
							<span className="hidden sm:block">&bull;</span>
							<span>By {post.author.name}</span>
						</>
					)}
				</div>
			</div>
			{/* Cover Image */}
			{!!coverImageSrc && (
				<div className="w-full my-4 sm:my-6 lg:my-8">
					<div className="relative aspect-video w-full overflow-hidden rounded-xl bg-gray-100 dark:bg-neutral-800">
						<Image
							src={coverImageSrc}
							alt={post.title}
							fill
							className="object-cover transition-transform duration-300 hover:scale-105"
							priority
							sizes="(max-width: 768px) 100vw, (max-width: 1200px) 80vw, 70vw"
						/>
					</div>
				</div>
			)}
			{/* Article Content */}
			<div className="prose prose-sm sm:prose-base lg:prose-lg xl:prose-xl prose-gray dark:prose-invert max-w-none prose-headings:text-black dark:prose-headings:text-white prose-p:leading-relaxed prose-pre:bg-gray-100 dark:prose-pre:bg-neutral-800">
				<MarkdownToHtml contentMarkdown={post.content.markdown} />
			</div>
			{/* Tags Section */}
			{(post.tags ?? []).length > 0 && (
				<div className="w-full border-t border-gray-200 dark:border-neutral-700 pt-6">
					<div className="flex flex-col gap-3">
						<span className="text-sm font-medium text-gray-500 dark:text-neutral-400">Tagged in</span>
						<div className="-mx-1 sm:mx-0">
							<ul className="flex items-center gap-2 max-w-full flex-wrap sm:flex-nowrap overflow-x-auto sm:overflow-x-auto px-1 sm:px-0">
								{tagsList}
							</ul>
						</div>
					</div>
				</div>
			)}
		</>
	);
};

const Page = (page: StaticPageFragment) => {
	const title = page.title;
	return (
		<>
			<Head>
				<title>{title}</title>
			</Head>
			<MarkdownToHtml contentMarkdown={page.content.markdown} />
		</>
	);
};

export default function PostOrPage({ publication, post, page }: Props) {
	if (!post && !page) {
		return <ErrorPage statusCode={404} />;
	}

	return (
		<AppProvider publication={publication} post={post}>
			<Layout>
			<Container className="mx-auto flex w-full max-w-4xl flex-col items-stretch gap-6 px-4 py-6 sm:gap-8 sm:px-6 sm:py-8 lg:gap-10 lg:px-8 lg:py-10">
				<PersonalHeader />
				<article className="flex flex-col items-start gap-6 sm:gap-8 lg:gap-10 pb-8 lg:pb-10">
					{post ? Post(publication, post) : Page(page)}
				</article>
				<Footer />
			</Container>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params) {
		throw new Error('No params');
	}
	const data = await request<SinglePostByPublicationQuery, SinglePostByPublicationQueryVariables>(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SinglePostByPublicationDocument,
		{
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
			slug: params.slug,
		},
	);

	// Extract the post data from the GraphQL response
	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const post = publication.post;
	if (!post) {
		const staticPageData = await request<PageByPublicationQuery, PageByPublicationQueryVariables>(
			process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
			PageByPublicationDocument,
			{
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				slug: params.slug,
			},
		);

		const page = staticPageData.publication?.staticPage;
		if (!page) {
			return {
				notFound: true,
			};
		}
		return {
			props: {
				post: null,
				page,
				publication,
			},
			revalidate: 1,
		};
	}

	return {
		props: {
			post,
			page: null,
			publication,
		},
		revalidate: 1,
	};
};

export async function getStaticPaths() {
	const data = await request<SlugPostsByPublicationQuery, SlugPostsByPublicationQueryVariables>(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SlugPostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const postSlugs = (data.publication?.posts.edges ?? []).map((edge) => edge.node.slug);

	return {
		paths: postSlugs.map((slug) => {
			return {
				params: {
					slug: slug,
				},
			};
		}),
		fallback: 'blocking',
	};
}
