import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { Waypoint } from 'react-waypoint';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Layout } from '../components/layout';
import { MinimalPosts } from '../components/minimal-posts';
import { PersonalHeader } from '../components/personal-theme-header';
import { DesktopSidebar } from '../components/desktop-sidebar';
import { EnhancedPostGrid } from '../components/enhanced-post-grid';
import { BreakingNewsBanner } from '../components/breaking-news-banner';
import { CategoryNav } from '../components/category-nav';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PageInfoFragment,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
	initialPageInfo: PageInfoFragment;
};

export default function Index({ publication, initialPosts, initialPageInfo }: Props) {
	const [posts, setPosts] = useState<PostFragment[]>(initialPosts);
	const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
	const [loadedMore, setLoadedMore] = useState(false);

	const loadMore = async () => {
		const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{
				first: 20,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				after: pageInfo.endCursor,
			},
		);
		if (!data.publication) {
			return;
		}
		const newPosts = data.publication.posts.edges.map((edge) => edge.node);
		setPosts([...posts, ...newPosts]);
		setPageInfo(data.publication.posts.pageInfo);
		setLoadedMore(true);
	};
	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>{publication.title}</title>
					<meta
						name="description"
						content={
							publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
						}
					/>
					<meta property="twitter:card" content="summary_large_image"/>
					<meta property="twitter:title" content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'} />
					<meta property="twitter:description" content={publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`} />
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				{/* Breaking News Banner */}
				{posts.length > 0 && (
					<BreakingNewsBanner posts={posts} />
				)}

				{/* Hero Section with Responsive Design */}
				<div className="bg-gradient-to-br from-primary-50 via-white to-primary-50 dark:from-neutral-900 dark:via-neutral-800 dark:to-neutral-900">
					<Container className="mx-auto flex max-w-7xl flex-col items-stretch gap-10 px-5 py-10">
						<PersonalHeader />
					</Container>
				</div>

				{/* Category Navigation */}
				{posts.length > 0 && (
					<CategoryNav posts={posts} />
				)}

				{/* Main Content with Sidebar Layout */}
				<Container className="mx-auto max-w-7xl px-5 py-10">
					{posts.length > 0 && (
						<div className="flex flex-col xl:flex-row gap-12">
							{/* Main Content */}
							<main className="flex-1 space-y-12">
								{/* Featured Article Hero */}
								{posts.length > 0 && (
									<section className="space-y-6">
										<div className="flex items-center justify-between">
											<h2 className="text-3xl lg:text-4xl font-bold text-gray-900 dark:text-white">
												⭐ Featured Story
											</h2>
											<div className="hidden lg:flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
												<div className="w-2 h-2 bg-red-500 rounded-full animate-pulse"></div>
												<span className="font-medium">LIVE</span>
											</div>
										</div>
										<div className="bg-white dark:bg-neutral-900 rounded-3xl border border-gray-200 dark:border-neutral-700 overflow-hidden shadow-xl hover:shadow-2xl transition-all duration-500 group">
											<MinimalPosts context="home" posts={posts.slice(0, 1)} />
										</div>
									</section>
								)}

								{/* Latest Stories Grid */}
								{posts.length > 1 && (
									<section className="space-y-8">
										<div className="flex items-center justify-between">
											<h2 className="text-2xl lg:text-3xl font-bold text-gray-900 dark:text-white">
												📰 Latest Stories
											</h2>
											<div className="flex items-center gap-3">
												<span className="text-sm text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-neutral-800 px-3 py-1 rounded-full">
													{posts.length - 1} articles
												</span>
												<div className="hidden sm:flex items-center text-xs text-gray-400 dark:text-gray-500">
													<span className="w-2 h-2 bg-green-500 rounded-full mr-2"></span>
													Updated now
												</div>
											</div>
										</div>
										<EnhancedPostGrid 
											posts={posts.slice(1)} 
											layout="grid"
											showExcerpt={true}
											showMetrics={true}
										/>
									</section>
								)}
							</main>

							{/* Sidebar - Hidden on mobile/tablet, visible on desktop */}
							<aside className="hidden xl:block xl:w-96 flex-shrink-0">
								<div className="sticky top-24">
									<DesktopSidebar posts={posts} />
								</div>
							</aside>
						</div>
					)}

					{/* Load More Button */}
					{!loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
						<div className="text-center py-8">
							<button 
								onClick={loadMore}
								className="inline-flex items-center px-6 py-3 bg-primary-500 hover:bg-primary-600 text-white font-medium rounded-lg transition-all duration-300 hover:shadow-lg hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2"
							>
								<svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
								</svg>
								Load More Articles
							</button>
						</div>
					)}

					{/* Auto Load More */}
					{loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
						<>
							<div className="text-center py-4">
								<div className="inline-flex items-center px-4 py-2 bg-gray-100 dark:bg-neutral-800 rounded-full text-sm text-gray-600 dark:text-gray-400">
									<div className="w-4 h-4 border-2 border-primary-500 border-t-transparent rounded-full animate-spin mr-2"></div>
									Loading more articles...
								</div>
							</div>
							<Waypoint onEnter={loadMore} bottomOffset={'10%'} />
						</>
					)}

				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 20,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const initialPosts = (publication.posts.edges ?? []).map((edge) => edge.node);

	return {
		props: {
			publication,
			initialPosts,
			initialPageInfo: publication.posts.pageInfo,
		},
		revalidate: 1,
	};
};
