import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { Waypoint } from 'react-waypoint';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Layout } from '../components/layout';
import { MinimalPosts } from '../components/minimal-posts';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PageInfoFragment,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
	initialPageInfo: PageInfoFragment;
};

export default function Index({ publication, initialPosts, initialPageInfo }: Props) {
	const [posts, setPosts] = useState<PostFragment[]>(initialPosts);
	const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
	const [loadedMore, setLoadedMore] = useState(false);

	const loadMore = async () => {
		const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{
				first: 20,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				after: pageInfo.endCursor,
			},
		);
		if (!data.publication) {
			return;
		}
		const newPosts = data.publication.posts.edges.map((edge) => edge.node);
		setPosts([...posts, ...newPosts]);
		setPageInfo(data.publication.posts.pageInfo);
		setLoadedMore(true);
	};
	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>{publication.title}</title>
					<meta
						name="description"
						content={
							publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
						}
					/>
					<meta property="twitter:card" content="summary_large_image"/>
					<meta property="twitter:title" content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'} />
					<meta property="twitter:description" content={publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`} />
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				{/* Hero Section with Responsive Design */}
				<div className="bg-gradient-to-br from-primary-50 via-white to-primary-50 dark:from-neutral-900 dark:via-neutral-800 dark:to-neutral-900">
					<Container className="mx-auto flex max-w-6xl flex-col items-stretch gap-10 px-5 py-10">
						<PersonalHeader />
					</Container>
				</div>

				{/* Main Content */}
				<Container className="mx-auto flex max-w-6xl flex-col items-stretch gap-10 px-5 py-10">
					{posts.length > 0 && (
						<div className="space-y-8">
							{/* Featured Post (First Post) */}
							{posts.length > 0 && (
								<section className="space-y-6">
									<div className="flex items-center justify-between">
										<h2 className="text-3xl font-bold text-gray-900 dark:text-white">
											✨ Featured Article
										</h2>
									</div>
									<div className="lg:grid lg:grid-cols-1 gap-8">
										<MinimalPosts context="home" posts={posts.slice(0, 1)} />
									</div>
								</section>
							)}

							{/* Recent Posts Grid */}
							{posts.length > 1 && (
								<section className="space-y-6">
									<div className="flex items-center justify-between">
										<h2 className="text-2xl font-bold text-gray-900 dark:text-white">
											📚 Recent Articles
										</h2>
										<span className="text-sm text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-neutral-800 px-3 py-1 rounded-full">
											{posts.length - 1} {posts.length - 1 === 1 ? 'post' : 'posts'}
										</span>
									</div>
									<div className="grid gap-8 sm:grid-cols-1 lg:grid-cols-2">
										<MinimalPosts context="home" posts={posts.slice(1)} />
									</div>
								</section>
							)}
						</div>
					)}

					{/* Load More Button */}
					{!loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
						<div className="text-center py-8">
							<button 
								onClick={loadMore}
								className="inline-flex items-center px-6 py-3 bg-primary-500 hover:bg-primary-600 text-white font-medium rounded-lg transition-all duration-300 hover:shadow-lg hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2"
							>
								<svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
								</svg>
								Load More Articles
							</button>
						</div>
					)}

					{/* Auto Load More */}
					{loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
						<>
							<div className="text-center py-4">
								<div className="inline-flex items-center px-4 py-2 bg-gray-100 dark:bg-neutral-800 rounded-full text-sm text-gray-600 dark:text-gray-400">
									<div className="w-4 h-4 border-2 border-primary-500 border-t-transparent rounded-full animate-spin mr-2"></div>
									Loading more articles...
								</div>
							</div>
							<Waypoint onEnter={loadMore} bottomOffset={'10%'} />
						</>
					)}

				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 20,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const initialPosts = (publication.posts.edges ?? []).map((edge) => edge.node);

	return {
		props: {
			publication,
			initialPosts,
			initialPageInfo: publication.posts.pageInfo,
		},
		revalidate: 1,
	};
};
